#!/bin/fish

set d (ls | grep -P "\d.md" | sort -r | head -c 1)

set d (math $d + 1)

test "$d" = "" && exit 1

read title

echo "---" >> $d.md
echo "title: $title" >> $d.md
echo "---" >> $d.md

echo "" >> $d.md
echo "<small>" (date -I) \*(date +%s)\*"</small>" >> $d.md

micro $d.md

fish "build" $d
